project:
  type: website
  resources: static

website:
  title: "MDAP Tech Time"
  navbar:
    left:
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true

execute:
  freeze: auto
